from __future__ import annotations

import json
import shutil
import subprocess
import tarfile
import tempfile
from pathlib import Path

from .interfaces import Cipher
from .records import iter_record_paths, unpack_record


MARKER = ".pdocs-readable-view"


class ViewError(RuntimeError):
    pass


def _extract_git_archive(archive_path: Path, destination: Path) -> None:
    root = destination.resolve()
    with tarfile.open(archive_path, "r") as archive:
        for member in archive.getmembers():
            target = (destination / member.name).resolve()
            if target != root and root not in target.parents:
                raise ViewError("Unsafe path in Git archive")
        archive.extractall(destination, filter="data")


def build_view(vault: Path, readable: Path, cipher: Cipher) -> int:
    readable.parent.mkdir(parents=True, exist_ok=True)
    if readable.exists() and not (readable / MARKER).exists():
        raise ViewError(f"Refusing to replace unmarked readable directory: {readable}")

    staging = Path(tempfile.mkdtemp(prefix=f".{readable.name}.", dir=readable.parent))
    index = []
    try:
        (staging / MARKER).write_text(
            "Generated by pdocs. Safe to replace.\n", encoding="utf-8"
        )
        for encrypted in iter_record_paths(vault):
            with tempfile.TemporaryDirectory() as temporary_dir:
                temporary = Path(temporary_dir)
                metadata = unpack_record(encrypted, cipher, temporary)
                record_dir = staging / metadata["id"]
                record_dir.mkdir(parents=True, exist_ok=True)
                filename = metadata["content"]["filename"]
                shutil.copy2(
                    temporary / "content" / filename,
                    record_dir / filename,
                )
                index.append(metadata)

        (staging / "INDEX.json").write_text(
            json.dumps(index, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        old = None
        if readable.exists():
            old = readable.with_name(f".{readable.name}.old")
            shutil.rmtree(old, ignore_errors=True)
            readable.rename(old)
        staging.rename(readable)
        if old:
            shutil.rmtree(old)
    except Exception:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    return len(index)


def build_view_from_head(vault: Path, readable: Path, cipher: Cipher) -> int:
    if not (vault / ".git").exists():
        raise ViewError(f"Vault is not a Git repository: {vault}")
    with tempfile.TemporaryDirectory() as temporary_dir:
        temporary = Path(temporary_dir)
        archive_path = temporary / "head.tar"
        snapshot = temporary / "snapshot"
        snapshot.mkdir()
        with archive_path.open("wb") as archive:
            result = subprocess.run(
                ["git", "archive", "--format=tar", "HEAD", "records"],
                cwd=vault,
                stdout=archive,
                stderr=subprocess.PIPE,
                text=False,
            )
        if result.returncode:
            detail = result.stderr.decode("utf-8", errors="replace").strip()
            raise ViewError(f"Unable to read vault HEAD: {detail}")
        _extract_git_archive(archive_path, snapshot)
        return build_view(snapshot, readable, cipher)
