from __future__ import annotations

import json
import re
import shutil
import subprocess
import tarfile
import tempfile
from pathlib import Path

from .interfaces import Cipher
from .records import iter_record_paths, unpack_record


MARKER = ".pdocs-readable-view"
UNSAFE_FILENAME = re.compile(r'[<>:"/\\|?*\x00-\x1f]')
WHITESPACE = re.compile(r"\s+")
DOMAIN_FOLDERS = {
    "identity-residence": "Identity and Residence",
    "education": "Education",
    "employment": "Employment",
    "household-housing": "Home and Housing",
    "finance-tax-banking": "Finance, Tax and Banking",
    "insurance-health": "Insurance and Health",
    "legal-administrative": "Legal and Administrative",
    "travel-purchases": "Travel and Purchases",
    "personal-correspondence": "Personal Correspondence",
}


class ViewError(RuntimeError):
    pass


def _truncate_utf8(value: str, max_bytes: int = 180) -> str:
    encoded = value.encode("utf-8")
    if len(encoded) <= max_bytes:
        return value
    return encoded[:max_bytes].decode("utf-8", errors="ignore").rstrip(" .-")


def _readable_name(value: str, *, fallback: str) -> str:
    value = UNSAFE_FILENAME.sub(" - ", value)
    value = WHITESPACE.sub(" ", value).strip(" .-")
    value = re.sub(r"(?:\s+-\s+){2,}", " - ", value)
    return _truncate_utf8(value or fallback)


def _domain_folder(domain: str) -> str:
    configured = DOMAIN_FOLDERS.get(domain, domain.replace("-", " ").title())
    return _readable_name(configured, fallback="Other")


def _presentation(metadata: dict) -> dict:
    presentation = metadata.get("presentation", {})
    return presentation if isinstance(presentation, dict) else {}


def _readable_folder(metadata: dict) -> Path:
    configured = _presentation(metadata).get("folder")
    if not isinstance(configured, str) or not configured.strip():
        return Path(_domain_folder(metadata["domain"]))
    parts = [
        _readable_name(part, fallback="Other")
        for part in Path(configured).parts
        if part not in {"", ".", ".."}
    ]
    return Path(*parts) if parts else Path(_domain_folder(metadata["domain"]))


def _readable_stem(metadata: dict) -> str:
    configured = _presentation(metadata).get("name")
    if not isinstance(configured, str) or not configured.strip():
        raise ViewError(
            f"Record {metadata['id']!r} has no explicit readable filename; "
            "run `pdocs record organize RECORD_ID --name NAME`"
        )
    return _readable_name(configured, fallback="Document")


def _document_suffix(filename: str) -> str:
    suffix = Path(filename).suffix
    return suffix.lower() if suffix else ""


def _extract_git_archive(archive_path: Path, destination: Path) -> None:
    root = destination.resolve()
    with tarfile.open(archive_path, "r") as archive:
        for member in archive.getmembers():
            target = (destination / member.name).resolve()
            if target != root and root not in target.parents:
                raise ViewError("Unsafe path in Git archive")
        archive.extractall(destination, filter="data")


def build_view(vault: Path, readable: Path, cipher: Cipher) -> int:
    readable.parent.mkdir(parents=True, exist_ok=True)
    if readable.exists() and not (readable / MARKER).exists():
        raise ViewError(f"Refusing to replace unmarked readable directory: {readable}")

    staging = Path(tempfile.mkdtemp(prefix=f".{readable.name}.", dir=readable.parent))
    index = []
    try:
        (staging / MARKER).write_text(
            "Generated by pdocs. Safe to replace.\n", encoding="utf-8"
        )
        with tempfile.TemporaryDirectory() as temporary_dir:
            extracted = Path(temporary_dir)
            records = []
            for position, encrypted in enumerate(iter_record_paths(vault)):
                temporary = extracted / str(position)
                metadata = unpack_record(encrypted, cipher, temporary)
                filename = metadata["content"]["filename"]
                records.append(
                    {
                        "metadata": metadata,
                        "content": temporary / "content" / filename,
                        "folder": _readable_folder(metadata),
                        "stem": _readable_stem(metadata),
                    }
                )

            used_names = set()
            for record in records:
                metadata = record["metadata"]
                folder = record["folder"]
                stem = record["stem"]
                folder_key = folder.as_posix().casefold()
                name_key = (folder_key, stem.casefold())
                if name_key in used_names:
                    raise ViewError(
                        f"Duplicate readable filename in {folder}: {stem!r}; "
                        "give each record an explicit unique name with "
                        "`pdocs record organize`"
                    )
                used_names.add(name_key)

                record_dir = staging / folder
                record_dir.mkdir(parents=True, exist_ok=True)
                metadata_dir = staging / ".metadata" / folder
                metadata_dir.mkdir(parents=True, exist_ok=True)
                document_name = f"{stem}{_document_suffix(record['content'].name)}"
                metadata_name = f"{stem}.json"
                shutil.copy2(record["content"], record_dir / document_name)
                (metadata_dir / metadata_name).write_text(
                    json.dumps(metadata, indent=2, ensure_ascii=False) + "\n",
                    encoding="utf-8",
                )
                index.append(
                    {
                        **metadata,
                        "view": {
                            "document": (Path(folder) / document_name).as_posix(),
                            "metadata": (
                                Path(".metadata") / folder / metadata_name
                            ).as_posix(),
                        },
                    }
                )

        (staging / "INDEX.json").write_text(
            json.dumps(index, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        old = None
        if readable.exists():
            old = readable.with_name(f".{readable.name}.old")
            shutil.rmtree(old, ignore_errors=True)
            readable.rename(old)
        staging.rename(readable)
        if old:
            shutil.rmtree(old)
    except Exception:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    return len(index)


def build_view_from_head(vault: Path, readable: Path, cipher: Cipher) -> int:
    if not (vault / ".git").exists():
        raise ViewError(f"Vault is not a Git repository: {vault}")
    with tempfile.TemporaryDirectory() as temporary_dir:
        temporary = Path(temporary_dir)
        archive_path = temporary / "head.tar"
        snapshot = temporary / "snapshot"
        snapshot.mkdir()
        records = subprocess.run(
            ["git", "ls-tree", "--name-only", "HEAD", "--", "records"],
            cwd=vault,
            text=True,
            capture_output=True,
        )
        if records.returncode:
            detail = records.stderr.strip()
            raise ViewError(f"Unable to read vault HEAD: {detail}")
        if not records.stdout.strip():
            return build_view(snapshot, readable, cipher)
        with archive_path.open("wb") as archive:
            result = subprocess.run(
                ["git", "archive", "--format=tar", "HEAD", "records"],
                cwd=vault,
                stdout=archive,
                stderr=subprocess.PIPE,
                text=False,
            )
        if result.returncode:
            detail = result.stderr.decode("utf-8", errors="replace").strip()
            raise ViewError(f"Unable to read vault HEAD: {detail}")
        _extract_git_archive(archive_path, snapshot)
        return build_view(snapshot, readable, cipher)
